config/routes.rb
Rails.application.routes.draw do
  
  
  get "login" => "sessions#new"
  
  delete "logout" => "sessions#destroy"
  
  post "login" => "sessions#create"

  get "signup" => 'users#new'
  
  get "home" => 'static_pages#home'
  
  get "cats" => 'static_pages#cats'

  get "help" => 'static_pages#help'
  
  get "about" => 'static_pages#about'

   root 'static_pages#home'
   
   
   resources :users

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save {self.email=email.downcase}
    
    
    
    VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:name, presence: true, length: {maximum: 50})
    validates(:email, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX})
    
    
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper #need to explicitly include your own helpers and modules, even those automatically generated
  
  def hello
    render text: "Hello!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #Sessions are resources but we are not storing them in the database so they are not "models"
  
  #get the log in page
  def new
  end
  
  #post log in credentials; save in temporary session
  #form for will place in params a hash of values associated withn key named :session
  def create
    #check if there is a user with the given email
    #and authenticate (using the authenticate method with the secure hashed password) the user
    @user=User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user #save the user's credentials in the (rails) session object
      redirect_to user_url(session[:user_id]) #now that we've saved the user's log in credentials, we can access them from anywhere in the code from the global sessions object
    else 
      flash[:danger] = "Incorrect log in"
      redirect_to login_url
    end
  
  end

  #log out; destroy the session
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def cats
  end
  
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    #create a new user to be initialized by form_for helper
    flash[:notice] = "Oh boy it is time to sign up"
    @user=User.new
  end
  
  #action that handles URLs that do not specify the id of a particular user (only supports get request)
  def index
    @all_users=User.all
  end
  
  #action that handles POST requests to the /users url (forms for new Users will route here; forms for old Users route to edit)
  def create
    @user=User.new(user_params)
    if @user.save 
      flash[:notice] = "You did it!"
      log_in @user
      redirect_to user_path(@user)
    else 
      flash[:error] = "You did not do it"
    render 'new'
  end #if/then blocks also require an "end"
  end
  
  #implicit return a filtered params hash containing the name, email, password and password_confirmation fields of the user that were passed in through the form in the raw
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  #action that handles URLs that specify the id of a particular user (i.e., get, edit, delete, users/2, users/7, etc)
  def show
    @the_user=User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:notice] = "No user with that id!"
    redirect_to cats_url #the benefit of naming a route is that it is easy to re_direct to it. pass the named url that is given to you when you define a named route (as in the examples in the routes file)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #@current_user-- we need the @ symbol always because that is what makes it a "class variable" that is accessible outside of the method body
    
    #store the user information in a rails session resource
    def log_in user
        session[:user_id]=user.id
    end
    
    
    #log out the current user.
    #delete the user's id from the user_id key of the sessions hash
    #set @current_user to nil
    def log_out
        session.delete :user_id
        @current_user=nil 
    end
    
    
    
    #retrieve the user that is currently logged in
    def current_user
        #caches the logged in user in a member variable (persists outside of the method) @current_user
        #if we have already cached current_user, just return it
        #note: use the find_by instead of the find method (even though the default search key for find is id) because find will fail if
        #the session does not contain a valid id.
       @current_user ||= User.find_by(id: session[:user_id])
    end
    
    
    def logged_in? 
       current_user!=nil 
    end
    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%provide(:title) %>
<head>
  <title>Welcome To The Page For | <%=yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% debug(params) if Rails.env.development? %>
  <% flash.each do |key, message| %>
  <h5><%= "#{key}: #{message}" %></h5>
  <% end %>
<%= yield %>

<p><%= link_to "Return to home page", root_url %></p>
<p>
</body>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<% provide(:title, "ABOUT")%>
<body>Page that knows what it's all about</body>

app/views/static_pages/cats.html.erb
<% provide(:title, "Cats") %>


<body><p>All of my thoughts about cats. Mostly I like them</p>
</body>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<% provide(:title, "HELP")%>
<body>Page for everything you might need help with</body>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<% provide(:title, "HOME")%>
<!-- all of the contents of the pages go inside the general yield tag of the layout file, in the body. i.e., I can't override the header that the layout files defines-->

<body>
    <hi>Sample Application</hi>
<p>Links to:</p>
<p><ul>
    <li>
    <%= link_to "Sign up", signup_url %>
</li>
<li>
    <%= link_to "About the application", about_url %>
</li>
<li>
    <%= link_to "About cats!", cats_url %>
</li>
   
    
    <!-- only display the link to the all users page to users who have logged in -->
    <% if logged_in? %>
   <li>
      <%= link_to "All of the users", users_url %>
   </li>
   
   <!-- links can specify HTTP verbs other than GET [which I think is the default for link_to]. here we automatically issue  DELETE http request to the linked url-->
   <li><%= link_to "Log out", logout_path, method: :delete %></li>
   <% else %> 
    <li>
        <%= link_to "Log in", login_url %>
    </li>
   <% end %>
    
  
</ul></p>
</body>

app/views/users/index.html.erb
<% provide(:title, "All users") %>


<h1>The Users of this application</h1>
<ul>
    <%= @all_users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<!DOCTYPE html>
<% provide(:title, "SIGNUP FOR COOL APP!") %>
<!-- use of the rails form_for helper -->
<h1> Fill out the form below to register.</h1>
<!-- be sure to use the %= command to INSERT the ruby code into the HTML template.-->
<%= form_for(@user) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%=f.email_field :email%>


<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Sign up!" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "Page of {#@the_user.name}")%>

This is the page for <%= @the_user.name %>. The user's email is <%= @the_user.email %>

<p><%= link_to "Back to users", users_path %></p>